FROM tomcat:9-jre8-alpine

ARG TIMEZONE=America/Sao_Paulo

RUN ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone

RUN rm -rf /usr/local/tomcat/webapps/ROOT

COPY artifacts/app.war /usr/local/tomcat/webapps/ROOT.war

CMD [ "catalina.sh", "run" ]

EXPOSE 8080